configs:
  config:
    file: ./config.yaml
secrets:
  broker_secrets:
    file: ./secrets/broker_secrets.yaml
  worker_secrets:
    file: ./secrets/worker_secrets.yaml

services:
  broker:
    image: ghcr.io/timeleaplabs/timeleap
    restart: always
    networks:
      - timeleap
    secrets:
      - source: broker_secrets
        target: /etc/timeleap/secrets.yaml
    configs:
      - source: config
        target: /etc/timeleap/config.yaml
    command: broker -s /etc/timeleap/secrets.yaml -c /etc/timeleap/config.yaml

  worker:
    image: ghcr.io/timeleaplabs/timeleap
    restart: always
    networks:
      - timeleap
    depends_on:
      - broker
    secrets:
      - source: worker_secrets
        target: /etc/timeleap/secrets.yaml
    configs:
      - source: config
        target: /etc/timeleap/config.yaml
    command: worker -s /etc/timeleap/secrets.yaml -c /etc/timeleap/config.yaml

networks:
  timeleap:
    external: false
